#gym Enterance Form 
name=input('Enter your name ') 
b_year=input('enter your birth year ')
age =2024 - int(b_year)
weight=input('enter your current weight ')
height=input('enter your height ')
exp=input('previous gym experience ')
inju=input('any injuries')
fees=500
plan=input('plan for membership (months) ')
total_fees=fees * int(plan) 
print("welcome to the aaaa gym ")
print('welcome ' + name)
print('your age is ',age  )
print('your weight is',weight)
print('your height is ',height)
print('pervious experious', exp)
print('any injuries',inju)
print('ýour gym fees will be ', total_fees)